"""Project paths and runtime asset resolution."""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None


if load_dotenv is not None:
    load_dotenv(Path(__file__).resolve().parents[1] / ".env")

ROOT_DIR = Path(os.environ.get("BADMINTON_PROJECT_ROOT", Path(__file__).resolve().parents[1])).resolve()
DATA_DIR = Path(os.environ.get("BADMINTON_DATA_DIR", ROOT_DIR / "data")).resolve()
CALIBRATION_DIR = Path(os.environ.get("BADMINTON_CALIBRATION_DIR", DATA_DIR / "calibration")).resolve()
LOG_DIR = Path(os.environ.get("BADMINTON_LOG_DIR", DATA_DIR / "logs")).resolve()
RAW_DIR = Path(os.environ.get("BADMINTON_RAW_DIR", DATA_DIR / "raw")).resolve()
OUTPUT_DIR = Path(os.environ.get("BADMINTON_OUTPUT_DIR", DATA_DIR / "output")).resolve()
MODEL_DIR = Path(os.environ.get("BADMINTON_MODEL_DIR", ROOT_DIR / "models")).resolve()


def ensure_runtime_dirs():
    """Create directories that the command-line tools write to."""
    for directory in (CALIBRATION_DIR, LOG_DIR, RAW_DIR, OUTPUT_DIR, MODEL_DIR):
        directory.mkdir(parents=True, exist_ok=True)


def project_path(*parts):
    """Return a path inside the project root."""
    return ROOT_DIR.joinpath(*parts)


def resolve_path(value, base_dir=ROOT_DIR):
    """Resolve a user/config path, treating relative paths as project-relative."""
    path = Path(os.fspath(value)).expanduser()
    if path.is_absolute():
        return path
    return (base_dir / path).resolve()


def as_project_relative(path):
    """Store project-local paths as portable POSIX strings."""
    path = Path(path).resolve()
    try:
        return path.relative_to(ROOT_DIR).as_posix()
    except ValueError:
        return str(path)


def resolve_existing_asset(env_name, candidates, required=False, description="asset"):
    """Resolve the first existing asset from an env var or candidate paths."""
    env_value = os.environ.get(env_name)
    if env_value:
        env_path = resolve_path(env_value)
        if env_path.exists():
            return env_path
        if required:
            raise FileNotFoundError(f"{description} configured by {env_name} was not found: {env_path}")

    resolved_candidates = [resolve_path(candidate) for candidate in candidates]
    for candidate in resolved_candidates:
        if candidate.exists():
            return candidate

    if required:
        locations = ", ".join(str(candidate) for candidate in resolved_candidates)
        raise FileNotFoundError(f"{description} not found. Checked: {locations}")
    return resolved_candidates[0]


def pose_model_path(required=True):
    """Return the MediaPipe pose landmarker model path."""
    return resolve_existing_asset(
        "BADMINTON_POSE_MODEL",
        [
            MODEL_DIR / "pose_landmarker.task",
            MODEL_DIR / "pose_landmarker_full.task",
            ROOT_DIR / "pose_landmarker.task",
        ],
        required=required,
        description="MediaPipe pose model",
    )


def yolo_model_path(model_name="yolov8s.pt"):
    """Return a YOLO model path/name that Ultralytics can load."""
    env_value = os.environ.get("BADMINTON_YOLO_MODEL")
    if env_value:
        return str(resolve_path(env_value))

    model_path = Path(model_name)
    if model_path.is_absolute() or model_path.parent != Path("."):
        return str(model_path)

    for candidate in (MODEL_DIR / model_name, ROOT_DIR / model_name, ROOT_DIR / "src" / model_name):
        if candidate.exists():
            return str(candidate)

    return model_name


def tracknet_weights_path(required=False):
    """Return the optional TrackNetV2 weights path."""
    return resolve_existing_asset(
        "BADMINTON_TRACKNET_WEIGHTS",
        [
            MODEL_DIR / "tracknet_weights.pt",
            ROOT_DIR / "src" / "tracknet_weights.pt",
        ],
        required=required,
        description="TrackNetV2 weights",
    )


def ball_speed_csv_path():
    """Return the generated shuttlecock speed CSV path."""
    env_value = os.environ.get("BADMINTON_BALL_SPEED_CSV")
    if env_value:
        return resolve_path(env_value)
    return LOG_DIR / "ball_speeds.csv"


def tracker_config_path():
    """Return the generated ByteTrack config path."""
    env_value = os.environ.get("BADMINTON_TRACKER_CONFIG")
    if env_value:
        return resolve_path(env_value)
    return LOG_DIR / "bytetrack.generated.yaml"
